# Uncomment the next line to define a global platform for your project
#platform :ios, '8.0'
use_frameworks!

def buildiOS

  targets = ['khala.iOS', 'khala.iOSTests']

  for item in targets do

    target item do
      pod 'SwiftLint'
      pod 'Khala', :path => '../'
      pod 'AModule', :path => './Compents/AModule/'
      pod 'BModule', :path => './Compents/BModule/'
      pod 'KhalaStore', :path => './Compents/KhalaStore/'
    end

  end

end


buildiOS
